const formatter = new Intl.NumberFormat('en-US', { maximumFractionDigits: 3 });

function localized(language, ar, en) {
    return language === 'ar' ? ar : en;
}

function output(value, label, details = '') {
    return { value: String(value), label, details };
}

function field(id, ar, en, placeholder, options = {}) {
    return Object.freeze({
        id,
        type: 'number',
        min: options.min ?? 0,
        max: options.max ?? 1e15,
        step: options.step ?? 0.01,
        label: Object.freeze({ ar, en }),
        unit: Object.freeze(options.unit ?? { ar: '', en: '' }),
        placeholder: String(placeholder),
    });
}

function tool(config) {
    return Object.freeze({
        id: config.id,
        category: 'engineering',
        icon: config.icon,
        title: Object.freeze(config.title),
        description: Object.freeze(config.description),
        note: Object.freeze(config.note),
        inputs: Object.freeze(config.inputs),
        calculate: config.calculate,
    });
}

function amount(value, unit = '') {
    return `${formatter.format(value)}${unit ? ` ${unit}` : ''}`;
}

const panelCount = tool({
    id: 'solar-panel-count-calculator',
    icon: 'PV',
    title: { ar: 'حاسبة عدد الألواح الشمسية', en: 'Solar Panel Count Calculator' },
    description: { ar: 'قدّر عدد الألواح اللازمة لتغطية استهلاك يومي.', en: 'Estimate panels needed to cover daily energy consumption.' },
    note: { ar: 'تعتمد النتيجة على ساعات الشمس وكفاءة النظام التقديرية.', en: 'Depends on peak-sun hours and estimated system efficiency.' },
    inputs: [
        field('dailyEnergy', 'الاستهلاك اليومي', 'Daily energy use', 20, { min: 0.001, unit: { ar: 'ك.و.س', en: 'kWh' } }),
        field('panelPower', 'قدرة اللوح', 'Panel power', 550, { min: 1, unit: { ar: 'واط', en: 'W' } }),
        field('sunHours', 'ساعات الشمس القصوى', 'Peak sun hours', 5, { min: 0.1, max: 24 }),
        field('efficiency', 'كفاءة النظام', 'System efficiency', 80, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
    ],
    calculate(values, language) {
        const dailyPerPanel = values.panelPower / 1000 * values.sunHours * values.efficiency / 100;
        return output(Math.ceil(values.dailyEnergy / dailyPerPanel), localized(language, 'عدد الألواح', 'Panels required'));
    },
});

const arrayOutput = tool({
    id: 'solar-array-daily-output-calculator',
    icon: 'kWh',
    title: { ar: 'حاسبة إنتاج المصفوفة الشمسية', en: 'Solar Array Daily Output Calculator' },
    description: { ar: 'قدّر الطاقة اليومية الناتجة عن مجموعة ألواح.', en: 'Estimate daily energy generated by a solar array.' },
    note: { ar: 'الإنتاج الفعلي يتأثر بالحرارة والظل والاتجاه.', en: 'Actual output varies with temperature, shade and orientation.' },
    inputs: [
        field('panels', 'عدد الألواح', 'Number of panels', 10, { min: 1, step: 1 }),
        field('panelPower', 'قدرة اللوح', 'Panel power', 550, { min: 1, unit: { ar: 'واط', en: 'W' } }),
        field('sunHours', 'ساعات الشمس القصوى', 'Peak sun hours', 5, { min: 0.1, max: 24 }),
        field('efficiency', 'كفاءة النظام', 'System efficiency', 80, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
    ],
    calculate: (values, language) => output(amount(values.panels * values.panelPower / 1000 * values.sunHours * values.efficiency / 100, 'kWh/day'), localized(language, 'الإنتاج اليومي', 'Daily output')),
});

const batteryBank = tool({
    id: 'battery-bank-capacity-calculator',
    icon: 'Ah',
    title: { ar: 'حاسبة سعة بنك البطاريات', en: 'Battery Bank Capacity Calculator' },
    description: { ar: 'احسب سعة البطاريات بالأمبير-ساعة من الطلب وأيام الاستقلالية.', en: 'Calculate battery amp-hours from energy demand and autonomy days.' },
    note: { ar: 'يؤخذ عمق التفريغ وكفاءة النظام في الاعتبار.', en: 'Accounts for depth of discharge and system efficiency.' },
    inputs: [
        field('dailyEnergy', 'الطاقة اليومية', 'Daily energy use', 5000, { min: 0.001, unit: { ar: 'واط.ساعة', en: 'Wh' } }),
        field('days', 'أيام الاستقلالية', 'Autonomy days', 2, { min: 0.1 }),
        field('voltage', 'جهد البنك', 'Bank voltage', 48, { min: 0.1, unit: { ar: 'فولت', en: 'V' } }),
        field('depth', 'عمق التفريغ المسموح', 'Allowed depth of discharge', 80, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
        field('efficiency', 'كفاءة النظام', 'System efficiency', 90, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
    ],
    calculate(values, language) {
        const ampHours = values.dailyEnergy * values.days
            / (values.voltage * values.depth / 100 * values.efficiency / 100);
        return output(amount(ampHours, 'Ah'), localized(language, 'السعة المطلوبة', 'Required capacity'));
    },
});

const batteryRuntime = tool({
    id: 'battery-runtime-calculator',
    icon: 'TIME',
    title: { ar: 'حاسبة زمن تشغيل البطارية', en: 'Battery Runtime Calculator' },
    description: { ar: 'قدّر مدة تشغيل حمل كهربائي من بطارية.', en: 'Estimate how long a battery can power an electrical load.' },
    note: { ar: 'النتيجة تقديرية وتتأثر بعمر البطارية ومعدل التفريغ.', en: 'Runtime varies with battery age and discharge rate.' },
    inputs: [
        field('voltage', 'جهد البطارية', 'Battery voltage', 12, { min: 0.1, unit: { ar: 'فولت', en: 'V' } }),
        field('ampHours', 'سعة البطارية', 'Battery capacity', 200, { min: 0.1, unit: { ar: 'أمبير.ساعة', en: 'Ah' } }),
        field('load', 'قدرة الحمل', 'Load power', 500, { min: 0.1, unit: { ar: 'واط', en: 'W' } }),
        field('depth', 'عمق التفريغ', 'Depth of discharge', 80, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
        field('efficiency', 'كفاءة التحويل', 'Conversion efficiency', 90, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
    ],
    calculate(values, language) {
        const hours = values.voltage * values.ampHours * values.depth / 100 * values.efficiency / 100 / values.load;
        return output(amount(hours, 'hours'), localized(language, 'زمن التشغيل التقديري', 'Estimated runtime'));
    },
});

const chargeTime = tool({
    id: 'battery-charge-time-calculator',
    icon: 'CHG',
    title: { ar: 'حاسبة زمن شحن البطارية', en: 'Battery Charge Time Calculator' },
    description: { ar: 'قدّر مدة شحن بطارية من سعتها وتيار الشاحن.', en: 'Estimate battery charging time from capacity and charger current.' },
    note: { ar: 'عامل الفقد يعوض انخفاض الكفاءة ومراحل الشحن النهائية.', en: 'Loss factor accounts for inefficiency and final charging stages.' },
    inputs: [
        field('capacity', 'سعة البطارية', 'Battery capacity', 100, { min: 0.1, unit: { ar: 'أمبير.ساعة', en: 'Ah' } }),
        field('state', 'نسبة الشحن الحالية', 'Current state of charge', 20, { max: 100, unit: { ar: '%', en: '%' } }),
        field('current', 'تيار الشاحن', 'Charger current', 20, { min: 0.1, unit: { ar: 'أمبير', en: 'A' } }),
        field('lossFactor', 'عامل الفقد', 'Loss factor', 15, { max: 100, unit: { ar: '%', en: '%' } }),
    ],
    calculate(values, language) {
        const missing = values.capacity * (1 - values.state / 100);
        return output(amount(missing / values.current * (1 + values.lossFactor / 100), 'hours'), localized(language, 'زمن الشحن', 'Charge time'));
    },
});

const inverter = tool({
    id: 'solar-inverter-size-calculator',
    icon: 'INV',
    title: { ar: 'حاسبة حجم الإنفرتر', en: 'Solar Inverter Size Calculator' },
    description: { ar: 'قدّر القدرة المستمرة المطلوبة للإنفرتر مع هامش أمان.', en: 'Estimate continuous inverter rating with safety headroom.' },
    note: { ar: 'تحقق منفصلًا من قدرة بدء المحركات والأحمال الحثية.', en: 'Check motor and inductive-load surge ratings separately.' },
    inputs: [
        field('continuousLoad', 'إجمالي الحمل المستمر', 'Continuous load', 3000, { unit: { ar: 'واط', en: 'W' } }),
        field('headroom', 'هامش الأمان', 'Safety headroom', 25, { max: 200, unit: { ar: '%', en: '%' } }),
    ],
    calculate: (values, language) => output(amount(values.continuousLoad * (1 + values.headroom / 100), 'W'), localized(language, 'قدرة الإنفرتر المقترحة', 'Suggested inverter rating')),
});

const payback = tool({
    id: 'solar-payback-period-calculator',
    icon: 'ROI',
    title: { ar: 'حاسبة فترة استرداد الطاقة الشمسية', en: 'Solar Payback Period Calculator' },
    description: { ar: 'قدّر سنوات استرداد تكلفة النظام من الوفر السنوي.', en: 'Estimate years to recover system cost from annual savings.' },
    note: { ar: 'لا يشمل تغير أسعار الطاقة أو الصيانة أو التمويل.', en: 'Excludes energy-price changes, maintenance and financing.' },
    inputs: [
        field('systemCost', 'تكلفة النظام', 'System cost', 12000),
        field('annualSavings', 'الوفر السنوي', 'Annual savings', 1800, { min: 0.001 }),
    ],
    calculate: (values, language) => output(amount(values.systemCost / values.annualSavings, 'years'), localized(language, 'فترة الاسترداد', 'Payback period')),
});

const storageDuration = tool({
    id: 'energy-storage-duration-calculator',
    icon: 'ESS',
    title: { ar: 'حاسبة مدة تخزين الطاقة', en: 'Energy Storage Duration Calculator' },
    description: { ar: 'احسب مدة تغذية حمل من سعة تخزين بالكيلوواط-ساعة.', en: 'Calculate load duration from storage capacity in kilowatt-hours.' },
    note: { ar: 'يؤخذ عمق التفريغ والكفاءة في الاعتبار.', en: 'Accounts for depth of discharge and efficiency.' },
    inputs: [
        field('capacity', 'سعة التخزين', 'Storage capacity', 10, { min: 0.001, unit: { ar: 'ك.و.س', en: 'kWh' } }),
        field('load', 'قدرة الحمل', 'Load power', 2, { min: 0.001, unit: { ar: 'كيلوواط', en: 'kW' } }),
        field('depth', 'عمق التفريغ', 'Depth of discharge', 90, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
        field('efficiency', 'الكفاءة', 'Efficiency', 90, { min: 1, max: 100, unit: { ar: '%', en: '%' } }),
    ],
    calculate: (values, language) => output(amount(values.capacity * values.depth / 100 * values.efficiency / 100 / values.load, 'hours'), localized(language, 'مدة التغذية', 'Storage duration')),
});

const dcCurrent = tool({
    id: 'dc-power-current-calculator',
    icon: 'DC',
    title: { ar: 'حاسبة تيار القدرة المستمرة', en: 'DC Power Current Calculator' },
    description: { ar: 'احسب التيار من القدرة والجهد في دائرة تيار مستمر.', en: 'Calculate current from power and voltage in a DC circuit.' },
    note: { ar: 'تستخدم العلاقة I = P ÷ V.', en: 'Uses I = P ÷ V.' },
    inputs: [
        field('power', 'القدرة', 'Power', 1200, { unit: { ar: 'واط', en: 'W' } }),
        field('voltage', 'الجهد', 'Voltage', 48, { min: 0.001, unit: { ar: 'فولت', en: 'V' } }),
    ],
    calculate: (values, language) => output(amount(values.power / values.voltage, 'A'), localized(language, 'التيار', 'Current')),
});

const voltageDrop = tool({
    id: 'dc-voltage-drop-calculator',
    icon: 'ΔV',
    title: { ar: 'حاسبة هبوط جهد التيار المستمر', en: 'DC Voltage Drop Calculator' },
    description: { ar: 'قدّر هبوط الجهد من التيار وطول المسار ومقاومة الموصل.', en: 'Estimate voltage drop from current, run length and conductor resistance.' },
    note: { ar: 'الطول المدخل لمسار واحد؛ تحسب الأداة الذهاب والعودة.', en: 'Enter one-way length; the calculation includes the return path.' },
    inputs: [
        field('current', 'التيار', 'Current', 20, { unit: { ar: 'أمبير', en: 'A' } }),
        field('length', 'طول المسار', 'One-way length', 15, { unit: { ar: 'م', en: 'm' } }),
        field('resistance', 'مقاومة الموصل لكل متر', 'Resistance per metre', 0.0033, { unit: { ar: 'أوم/م', en: 'Ω/m' } }),
        field('voltage', 'جهد النظام', 'System voltage', 48, { min: 0.001, unit: { ar: 'فولت', en: 'V' } }),
    ],
    calculate(values, language) {
        const drop = values.current * values.length * 2 * values.resistance;
        return output(amount(drop, 'V'), localized(language, 'هبوط الجهد', 'Voltage drop'), `${amount(drop / values.voltage * 100)}%`);
    },
});

const solarBatteryDefinitions = Object.freeze({
    [panelCount.id]: panelCount,
    [arrayOutput.id]: arrayOutput,
    [batteryBank.id]: batteryBank,
    [batteryRuntime.id]: batteryRuntime,
    [chargeTime.id]: chargeTime,
    [inverter.id]: inverter,
    [payback.id]: payback,
    [storageDuration.id]: storageDuration,
    [dcCurrent.id]: dcCurrent,
    [voltageDrop.id]: voltageDrop,
});

export { solarBatteryDefinitions };

// END OF FILE
